baseURL = "https://example.org/"
languageCode = "en-us"
theme = "montoya"
publishDir = "../docs"

[params.meta]
  title = "Dri Sommer"
  author = "Dri Sommer"
  description = "Dri Sommer - Directing and Editing"

[params]
  googleAnalyticsCode = "UA-XXXXXXXXX-X"
  
  # Theme Colors
  #  - MAIN PINK - #D1004D
  #  - SECOND MAIN YELLOW  - #EDC716
  #  - ACCENT BLUE -rgb(30, 97, 1)
  [params.colors]
    accentColor = "#EDC716"
    accentColorAlt = "#19AE47"

    darkBackground = "#D1004D"
    lightBackground = "#f5f9fc"
    
    darkText = "#000000"
    lightText = "#ffffff"
  # font sources
  # https://fonts.google.com/specimen/Splash?preview.text=DIRECTOR%20*%20EDITOR%20*%20DRI%20SOMMER&categoryFilters=Feeling:%2FExpressive%2FArtistic
  # https://fonts.google.com/specimen/Monoton?preview.text=DIRECTOR%20*%20EDITOR%20*%20DRI%20SOMMER&categoryFilters=Feeling:%2FExpressive%2FArtistic
  # https://fonts.google.com/specimen/Fredericka+the+Great?preview.text=DIRECTOR%20*%20EDITOR%20*%20DRI%20SOMMER&categoryFilters=Feeling:%2FExpressive%2FArtistic
  [params.fonts]
    primaryFont = "Newsreader"
    secondaryFont = "Tilt Prism"
    # Global multiplier for font sizes with vw units
    fontSizeMultiplier = "0.25"
    
  [params.fontSizes]
    # Title font sizes (vw values)
    headerTitle = "6"
    heroTitle = "24.15"
    bigTitle = "12"
    h1Size = "4.15"
    h2Size = "3"
    h3Size = "2"
    h4Size = "1"
    h5Size = "0.6"
    h6Size = "18px"
    bodySize = "16px"
    smallBodySize = "15px"
    captionSize = "12px"
    # Menu font sizes (vw values)
    menuSize = "30"
    menuSizeSmall = "35"
    # Showcase component font sizes
    showcaseTitle = "24px"
    showcaseGalleryTitle = "20px"
    showcaseTitleSmall = "18px"
    showcaseButton = "14px"
    showcaseCaption = "14px"
    showcaseProgress = "14px"
    showcaseSubtitleMobile = "16px"
    showcaseOverlappingTitleMobile = "0.5"
    # Responsive title variations
    nextHeroTitle = "22.15"
    
  [params.lineHeights]
    # Title line heights (vw values)
    heroLineHeight = "22"
    bigLineHeight = "7.5"
    h1LineHeight = "4.5"
    h2LineHeight = "3.5"
    h3LineHeight = "2.5"
    h4LineHeight = "1.6"
    h5LineHeight = "1.5"
    h6LineHeight = "36px"
    bodyLineHeight = "30px"
    # Responsive line height variations
    nextHeroLineHeight = "14.5"
    responsiveHeroLineHeight = "20.5"
    responsiveNextHeroLineHeight = "12.5"
    
  [params.layout]
    # Layout spacing and dimensions (vw values)
    galleryPadding = "42"
    galleryPaddingSmall = "35"
    titleMarginLeft = "-0.6"
    minElementWidth = "3"
    
  [params.dimensions]
    # Gallery item dimensions (vw values)
    galleryItemSmall = "18"
    galleryItemStandard = "22"
    galleryItemMedium = "33"
    galleryItemLarge = "44"

# Main navigation menu
[menu]
  [[menu.main]]
    name = "Commercials"
    url = "/commercials/"
    weight = 10

  [[menu.main]]
    name = "Music Videos"
    url = "/music-videos/"
    weight = 20

  [[menu.main]]
    name = "Immersive"
    url = "/immersive/"
    weight = 30
  
    [[menu.main]]
    name = "About Dri"
    url = "/about/"
    weight = 40

[params.preloader]
  centerLine = "Loading"
  percentageIntro = "Please wait, content is loading"

[params.footer]
  backTopText = "Back Top"
  copyright = "2025 © Dri Sommer. All rights reserved."
  followUsText = "Follow Us"
  showSocials = false  # Set to false to hide the social links section

[[params.footer.socialLinks]]
  name = "Dribbble"
  code = "Db"
  url = "https://www.dribbble.com/drisommer"

[[params.footer.socialLinks]]
  name = "Twitter"
  code = "Tw"
  url = "https://www.twitter.com/drisommerdesign"

[[params.footer.socialLinks]]
  name = "Instagram"
  code = "In"
  url = "https://www.instagram.com/drisommer/"
  
# Contact information that acts as fallback if the markdown doesn't define contacts

[[params.contacts]]
info = "@drisommer"
name = "instagram"
icon = "fa-brands fa-instagram"
url = "https://www.instagram.com/drisommer/"
type = "link"

[[params.contacts]]
info = "Los Angeles 🛫 São Paulo"
name = "usually hanging out in one of these places"
icon = "fa-location-dot"
type = "text"

[[params.contacts]]
info = "drika.sommer@gmail.com"
name = "shoot me an email"
icon = "fa-paper-plane"
type = "text"

